users = [
    {
        "id": "1",
        "name": "John",
        "age": "30",
        "city": "New York",
        "country": "USA",
        "language": "Python",
        "framework": "Django",
        "is_active": 'True',
        "email": "zjzLs@example.com",
        "phone": "1234567890"
    },
    {
        "id": "2",
        "name": "Jane",
        "age": "25",
        "city": "London",
        "country": "UK",
        "language": "JavaScript",
        "framework": "React",
        "is_active": 'False',
        "email": "XUwSj@example.com",
        "phone": "9876543210"
    },
    {
        "id": "3",
        "name": "Bob",
        "age": "40",
        "city": "Paris",
        "country": "France",
        "language": "Java",
        "framework": "Spring",
        "is_active": 'True',
        "email": "bob@example.com",
        "phone": "4567890123"
    },
    {
        "id": "4",
        "name": "Alice",
        "age": "35",
        "city": "Berlin",
        "country": "Germany",
        "language": "C++",
        "framework": "Qt",
        "is_active": 'False',
        "email": "alice@example.com",
        "phone": "3216549870"
    },
    {
        "id": "5",
        "name": "Mike",
        "age": "45",
        "city": "Moscow",
        "country": "Russia",
        "language": "C#",
        "framework": "ASP.NET",
        "is_active": 'True',
        "email": "mike@example.com",
        "phone": "6543217890"
    },
    {
        "id": "6",
        "name": "Sarah",
        "age": "28",
        "city": "Tokyo",
        "country": "Japan",
        "language": "PHP",
        "framework": "Laravel",
        "is_active": 'False',
        "email": "sarah@example.com",
        "phone": "7890123456"
    },
    {
        "id": "7",
        "name": "David",
        "age": "32",
        "city": "Sydney",
        "country": "Australia",
        "language": "Ruby",
        "framework": "Ruby on Rails",
        "is_active": 'True',
        "email": "david@example.com",
        "phone": "4561237890"
    },
    {
        "id": "8",
        "name": "Emma",
        "age": "29",
        "city": "Toronto",
        "country": "Canada",
        "language": "Swift",
        "framework": "UIKit",
        "is_active": 'True',
        "email": "emma@example.com",
        "phone": "0123456789"
    },
    {
        "id": "9",
        "name": "Liam",
        "age": "36",
        "city": "Dublin",
        "country": "Ireland",
        "language": "Go",
        "framework": "Gin",
        "is_active": 'False',
        "email": "liam@example.com",
        "phone": "9871234560"
    },
    {
        "id": "10",
        "name": "Olivia",
        "age": "27",
        "city": "Cape Town",
        "country": "South Africa",
        "language": "Kotlin",
        "framework": "Spring Boot",
        "is_active": 'True',
        "email": "olivia@example.com",
        "phone": "6547891230"
    },
    {
        "id": "11",
        "name": "Sophia",
        "age": "31",
        "city": "Buenos Aires",
        "country": "Argentina",
        "language": "Rust",
        "framework": "Actix",
        "is_active": 'True',
        "email": "sophia@example.com",
        "phone": "3219876540"
    },
    {
        "id": "12",
        "name": "Noah",
        "age": "38",
        "city": "Seoul",
        "country": "South Korea",
        "language": "TypeScript",
        "framework": "Angular",
        "is_active": 'False',
        "email": "noah@example.com",
        "phone": "1472583690"
    },
    {
        "id": "13",
        "name": "Lucas",
        "age": "22",
        "city": "Madrid",
        "country": "Spain",
        "language": "Scala",
        "framework": "Play",
        "is_active": 'True',
        "email": "lucas@example.com",
        "phone": "1357924680"
    },
    {
        "id": "14",
        "name": "Ava",
        "age": "26",
        "city": "Rome",
        "country": "Italy",
        "language": "Haskell",
        "framework": "Yesod",
        "is_active": 'True',
        "email": "ava@example.com",
        "phone": "2468013579"
    },
    {
        "id": "15",
        "name": "Elijah",
        "age": "34",
        "city": "Nairobi",
        "country": "Kenya",
        "language": "Clojure",
        "framework": "Compojure",
        "is_active": 'False',
        "email": "elijah@example.com",
        "phone": "3571594680"
    },
    {
        "id": "16",
        "name": "Mia",
        "age": "29",
        "city": "Wellington",
        "country": "New Zealand",
        "language": "Perl",
        "framework": "Dancer",
        "is_active": 'True',
        "email": "mia@example.com",
        "phone": "4682013579"
    },
    {
        "id": "17",
        "name": "Isabella",
        "age": "41",
        "city": "Cairo",
        "country": "Egypt",
        "language": "Swift",
        "framework": "Vapor",
        "is_active": 'True',
        "email": "isabella@example.com",
        "phone": "5798642031"
    },
    {
        "id": "18",
        "name": "James",
        "age": "37",
        "city": "Singapore",
        "country": "Singapore",
        "language": "Go",
        "framework": "Echo",
        "is_active": 'False',
        "email": "james@example.com",
        "phone": "6842109753"
    },
    {
        "id": "19",
        "name": "Charlotte",
        "age": "24",
        "city": "Lisbon",
        "country": "Portugal",
        "language": "JavaScript",
        "framework": "Vue.js",
        "is_active": 'True',
        "email": "charlotte@example.com",
        "phone": "7893216540"
    },
    {
        "id": "20",
        "name": "Benjamin",
        "age": "30",
        "city": "Brussels",
        "country": "Belgium",
        "language": "PHP",
        "framework": "Symfony",
        "is_active": 'True',
        "email": "benjamin@example.com",
        "phone": "3216549871"
    },
    {
        "id": "19",
        "name": "Charlotte",
        "age": "24",
        "city": "Lisbon",
        "country": "Portugal",
        "language": "JavaScript",
        "framework": "Vue.js",
        "is_active": 'True',
        "email": "charlotte@example.com",
        "phone": "7893216540"
    },
    {
        "id": "20",
        "name": "Benjamin",
        "age": "30",
        "city": "Brussels",
        "country": "Belgium",
        "language": "PHP",
        "framework": "Symfony",
        "is_active": 'True',
        "email": "benjamin@example.com",
        "phone": "3216549871"
    },
    {
        "id": "21",
        "name": "Olivia",
        "age": "27",
        "city": "Barcelona",
        "country": "Spain",
        "language": "Python",
        "framework": "Django",
        "is_active": 'True',
        "email": "olivia@example.com",
        "phone": "4567891230"
    },
    {
        "id": "22",
        "name": "Ethan",
        "age": "32",
        "city": "Berlin",
        "country": "Germany",
        "language": "Java",
        "framework": "Spring",
        "is_active": 'True',
        "email": "ethan@example.com",
        "phone": "1234567890"
    },
    {
        "id": "23",
        "name": "Sophia",
        "age": "28",
        "city": "Amsterdam",
        "country": "Netherlands",
        "language": "C#",
        "framework": "ASP.NET",
        "is_active": 'False',
        "email": "sophia@example.com",
        "phone": "9876543210"
    },
    {
        "id": "24",
        "name": "William",
        "age": "35",
        "city": "Oslo",
        "country": "Norway",
        "language": "Ruby",
        "framework": "Ruby on Rails",
        "is_active": 'True',
        "email": "william@example.com",
        "phone": "6543217890"
    },
    {
        "id": "25",
        "name": "Ava",
        "age": "22",
        "city": "Stockholm",
        "country": "Sweden",
        "language": "Go",
        "framework": "Gin",
        "is_active": 'True',
        "email": "ava@example.com",
        "phone": "7894561230"
    },
    {
        "id": "26",
        "name": "Liam",
        "age": "29",
        "city": "Dublin",
        "country": "Ireland",
        "language": "Kotlin",
        "framework": "Ktor",
        "is_active": 'True',
        "email": "liam@example.com",
        "phone": "6549873210"
    },
    {
        "id": "27",
        "name": "Mia",
        "age": "26",
        "city": "Toronto",
        "country": "Canada",
        "language": "Swift",
        "framework": "SwiftUI",
        "is_active": 'True',
        "email": "mia@example.com",
        "phone": "3217896540"
    },
    {
        "id": "28",
        "name": "Noah",
        "age": "31",
        "city": "Sydney",
        "country": "Australia",
        "language": "TypeScript",
        "framework": "Angular",
        "is_active": 'True',
        "email": "noah@example.com",
        "phone": "4561237890"
    },
    {
        "id": "29",
        "name": "Isabella",
        "age": "25",
        "city": "Auckland",
        "country": "New Zealand",
        "language": "Rust",
        "framework": "Rocket",
        "is_active": 'False',
        "email": "isabella@example.com",
        "phone": "7893214560"
    },
    {
        "id": "30",
        "name": "James",
        "age": "33",
        "city": "Madrid",
        "country": "Spain",
        "language": "Scala",
        "framework": "Play",
        "is_active": 'True',
        "email": "james@example.com",
        "phone": "6547891230"
    },
    {
        "id": "31",
        "name": "Emma",
        "age": "23",
        "city": "Copenhagen",
        "country": "Denmark",
        "language": "Elixir",
        "framework": "Phoenix",
        "is_active": 'True',
        "email": "emma@example.com",
        "phone": "3214567890"
    },
    {
        "id": "32",
        "name": "Lucas",
        "age": "36",
        "city": "Vienna",
        "country": "Austria",
        "language": "Haskell",
        "framework": "Yesod",
        "is_active": 'False',
        "email": "lucas@example.com",
        "phone": "9873216540"
    },
    {
        "id": "33",
        "name": "Avery",
        "age": "28",
        "city": "Prague",
        "country": "Czech Republic",
        "language": "C++",
        "framework": "Qt",
        "is_active": 'True',
        "email": "avery@example.com",
        "phone": "6541237890"
    },
    {
        "id": "34",
        "name": "Mason",
        "age": "30",
        "city": "Warsaw",
        "country": "Poland",
        "language": "Go",
        "framework": "Fiber",
        "is_active": 'True',
        "email": "mason@example.com",
        "phone": "3219876540"
    },
    {
        "id": "35",
        "name": "Ella",
        "age": "22",
        "city": "Oslo",
        "country": "Norway",
        "language": "Perl",
        "framework": "Dancer",
        "is_active": 'True',
        "email": "ella@example.com",
        "phone": "4563217890"
    },
    {
        "id": "36",
        "name": "Jackson",
        "age": "31",
        "city": "Helsinki",
        "country": "Finland",
        "language": "Clojure",
        "framework": "Compojure",
        "is_active": 'False',
        "email": "jackson@example.com",
        "phone": "7894561230"
    },
    {
        "id": "37",
        "name": "Grace",
        "age": "29",
        "city": "Lisbon",
        "country": "Portugal",
        "language": "F#",
        "framework": "Giraffe",
        "is_active": 'True',
        "email": "grace@example.com",
        "phone": "6547893210"
    },
    {
        "id": "38",
        "name": "Logan",
        "age": "34",
        "city": "Athens",
        "country": "Greece",
        "language": "Swift",
        "framework": "Vapor",
        "is_active": 'True',
        "email": "logan@example.com",
        "phone": "3216549870"
    },
    {
        "id": "39",
        "name": "Zoe",
        "age": "27",
        "city": "Dubai",
        "country": "UAE",
        "language": "Objective-C",
        "framework": "Cocoa",
        "is_active": 'True',
        "email": "zoe@example.com",
        "phone": "4567893210"
    },
    {
        "id": "40",
        "name": "Henry",
        "age": "38",
        "city": "Bangkok",
        "country": "Thailand",
        "language": "SQL",
        "framework": "MySQL",
        "is_active": 'True',
        "email": "henry@example.com",
        "phone": "9876541230"
    },
    {
        "id": "70",
        "name": "Abigail",
        "age": "33",
        "city": "Seattle",
        "country": "USA",
        "language": "JavaScript",
        "framework": "Express",
        "is_active": 'True',
        "email": "abigail@example.com",
        "phone": "1234567890",
    },
    {
        "id": "71",
        "name": "Ethan",
        "age": "28",
        "city": "Paris",
        "country": "France",
        "language": "Python",
        "framework": "Django",
        "is_active": 'True',
        "email": "ethan@example.com",
        "phone": "9876543210",
    },
    {
        "id": "72",
        "name": "Charlotte",
        "age": "35",
        "city": "Cairo",
        "country": "Egypt",
        "language": "C++",
        "framework": "Qt",
        "is_active": 'True',
        "email": "charlotte@example.com",
        "phone": "4567891230",
    },
    {
        "id": "73",
        "name": "Alexander",
        "age": "40",
        "city": "Berlin",
        "country": "Germany",
        "language": "Java",
        "framework": "Spring",
        "is_active": 'True',
        "email": "alexander@example.com",
        "phone": "7890123456",
    },
    {
        "id": "74",
        "name": "Sofia",
        "age": "29",
        "city": "Stockholm",
        "country": "Sweden",
        "language": "Go",
        "framework": "Gin",
        "is_active": 'True',
        "email": "sofia@example.com",
        "phone": "6543217890",
    },
    {
        "id": "75",
        "name": "Mateo",
        "age": "25",
        "city": "Mexico City",
        "country": "Mexico",
        "language": "Kotlin",
        "framework": "Ktor",
        "is_active": 'True',
        "email": "mateo@example.com",
        "phone": "9871234560",
    },
    {
        "id": "76",
        "name": "Ava",
        "age": "22",
        "city": "Tokyo",
        "country": "Japan",
        "language": "TypeScript",
        "framework": "Angular",
        "is_active": 'True',
        "email": "ava@example.com",
        "phone": "6549873210",
    },
    {
        "id": "77",
        "name": "Isabella",
        "age": "31",
        "city": "London",
        "country": "UK",
        "language": "JavaScript",
        "framework": "React",
        "is_active": 'True',
        "email": "isabella@example.com",
        "phone": "3216549870",
    },
    {
        "id": "78",
        "name": "Julian",
        "age": "36",
        "city": "New York",
        "country": "USA",
        "language": "Python",
        "framework": "Flask",
        "is_active": 'True',
        "email": "julian@example.com",
        "phone": "1234567890",
    },
    {
        "id": "79",
        "name": "Evelyn",
        "age": "26",
        "city": "Sydney",
        "country": "Australia",
        "language": "Java",
        "framework": "Spring",
        "is_active": 'True',
        "email": "evelyn@example.com",
        "phone": "9876543210",
    },
    {
        "id": "80",
        "name": "Gabriel",
        "age": "38",
        "city": "Toronto",
        "country": "Canada",
        "language": "JavaScript",
        "framework": "Vue.js",
        "is_active": 'True',
        "email": "gabriel@example.com",
        "phone": "6543217890",
    },
    {
        "id": "81",
        "name": "Olivia",
        "age": "24",
        "city": "Los Angeles",
        "country": "USA",
        "language": "C++",
        "framework": "Qt",
        "is_active": 'True',
        "email": "olivia@example.com",
        "phone": "3216549870",
    },
    {
        "id": "82",
        "name": "Benjamin",
        "age": "30",
        "city": "Paris",
        "country": "France",
        "language": "Go",
        "framework": "Gin",
        "is_active": 'True',
        "email": "benjamin@example.com",
        "phone": "9871234560",
    }
]



scema = ["id", "name", "age", "city", "country", "language", "framework", "is_active", "email", "phone"]
